name: Daily Content Generation

on:
  schedule:
    # Run at 00:00 KST (15:00 UTC) every day
    - cron: '0 15 * * *'
  workflow_dispatch: # Allow manual trigger

env:
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
  WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}

jobs:
  generate-content:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.pnpm-store
        key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-
    
    - name: Install pnpm
      run: npm install -g pnpm
    
    - name: Install dependencies
      run: pnpm install
    
    - name: Generate Prisma Client
      run: pnpm prisma generate
    
    - name: Run daily content generator
      run: node scripts/daily-content-generator.js
      
    - name: Commit topic index update
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add scripts/topic-index.json || true
        git commit -m "Update topic index [skip ci]" || true
        
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
        
    - name: Trigger Vercel redeploy (if webhook exists)
      if: env.REDEPLOY_WEBHOOK_URL
      run: |
        curl -X POST ${{ secrets.REDEPLOY_WEBHOOK_URL }}
      env:
        REDEPLOY_WEBHOOK_URL: ${{ secrets.REDEPLOY_WEBHOOK_URL }}